# Generated by Django 4.2.5 on 2023-09-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_creditscore_id_alter_creditscore_adhaar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTypeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Car', 'Car Loan'), ('Home', 'Home Loan'), ('Education', 'Educational Loan'), ('Personal', 'Personal Loan')], max_length=20, unique=True)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Car', 'Car Loan'), ('Home', 'Home Loan'), ('Education', 'Educational Loan'), ('Personal', 'Personal Loan')], max_length=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
