# Generated by Django 4.2.5 on 2023-09-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_emi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanTypeLimit',
        ),
    ]
