# Generated by Django 4.2.5 on 2023-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_delete_loantypelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emi',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emi',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
