# Generated by Django 4.2.5 on 2023-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_emi_amount_due_emi_amount_paid_emi_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='emi_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
