# Generated by Django 4.2.5 on 2023-09-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loanapplication_loan_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emi',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='paid',
        ),
        migrations.AlterField(
            model_name='emi',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loanapplication'),
        ),
    ]
