# Generated by Django 4.2.5 on 2023-09-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_creditscore_id_alter_creditscore_adhaar_id'),
        ('loan', '0009_remove_emi_amount_due_remove_emi_emi_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.customer'),
        ),
    ]
