# Generated by Django 4.2.5 on 2023-09-17 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('adhaar_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=30)),
                ('annual_income', models.IntegerField(default=0, verbose_name='Annual Income')),
            ],
        ),
    ]
